Vexu/arocc

src/lib.zig
This is quite a simple PR - but just makes the parser part of the public-facing API.
=> Expose parser in lib.zig

src/Diagnostics.zig, src/Parser.zig, src/Tree.zig, src/Type.zig, test/README.MD, test/cases/assignment.c, test/cases/binary expressions.c, test/cases/type_resolution.c, test/runner.zig
Adds a new implicit cast type `qual_cast` for implicit casts due to mismatching pointers on conditional expressions
Adds a new implicit cast type `null_to_pointer` to convert `0` to a pointer of appropriate type
Adds a way to test expression types.
=> condexpr type resolution + null ptr cast + some tests

src/Diagnostics.zig, src/Parser.zig, src/Tree.zig, test/cases/static assert messages.c
Compile error if the condition is not constant
Nicer error message if the message is not included (this is a C++17 extension)
=> improve _Static_assert

src/Diagnostics.zig, src/Parser.zig, src/Tokenizer.zig, src/Type.zig, test/cases/incorrect typeof usage.c, test/cases/typeof.c
Two questions:
1) bare `typeof` is a GNU extension, so if GNU extensions are turned off it should be an identifier. But it doesn't seem like the Tokenizer has any concept of language options - is that something we should add?
2) I'm not storing the typeof nodes in the AST. I think that would be fine for `translate-c` but other things may want them. However I think it might be a more invasive change since it means we'd need a way to link types to nodes.
=> Parser: add typeof support

src/LangOpts.zig, src/Parser.zig, src/Tokenizer.zig, test/cases/gnu alignof.c, test/cases/sizeof alignof.c, test/cases/typeof.c, test/runner.zig
Note: `sizeof` and `_Alignof` previously used `unExpr` to parse their expression but it seems like it should be `assignExpr` for them (like `genericSelection` uses). If they actually should be `unExpr` I can change them back.
=> Do not evaluate typeof/sizeof/alignof arguments

src/Diagnostics.zig, src/Parser.zig, src/Tokenizer.zig, src/Tree.zig, test/cases/builtin choose expr.c
Similar to conditional operator, except:
1. First argument must be an integer constant
2. return type matches that of chosen expression and does not undergo promotion
3. unchosen expression is not evaluated
4. can return an lvalue if the chosen expression is an lvalue
=> Parser: implement __builtin_choose_expr

src/Compilation.zig, src/LangOpts.zig, test/cases/predefined macros.c, test/runner.zig
Use correct value of `__STDC_VERSION__`
Add placeholder values for `__DATE__` and `__TIME__`
Update test runner to create a new compilation for each test since the predefined macros can change based on the test.
=> Update predefined macros

src/Parser.zig, src/Type.zig, test/cases/parser using typeof types.c, test/cases/typeof quals.c, test/cases/typeof.c
Add two new type specifiers: `typeof_type` and `typeof_expr`, which
are the types returned by `typeof` (depending on whether it's called
with a type or an expression)
This allows us to track the underlying type or expression that was
used.
=> Parser: improve typeof support

src/Parser.zig, test/cases/redefinitions.c
Check for function redefinitions having exactly same signature, i,e redefinition of exact same function, which were previously missing from the parser. Test case included.
```c
int foo(int a) { 
return 10; 
}
int foo(int a) { 
return a; 
}
```
=> Parser: Check for function redefinition for same signature

src/Preprocessor.zig, test/cases/unterminated macro function at eof.c
=> Preprocessor: Ensure MacroArguments are always fully de-init'ed

src/Preprocessor.zig, test/cases/hash_hash at func macro start.c
=> Preprocessor: detect ## at the beginning of a func macro

src/Diagnostics.zig, test/runner.zig
Right now, warnings and errors are showed as follows:
```sh-session
warning: implicit declaration of function '_Static_asset' is invalid in C99
error: multi-character character constant
```
This PR adds the corresponding CLI option to explicitly enable the error or warning setting besides the messages as follows:
```sh-session
warning: implicit declaration of function '_Static_asset' is invalid in C99 [-Wimplicit-function-declaration]
error: multi-character character constant [-Werror=multichar]
```
=> Diagnostics: show the respective warning and error options besides warning and error messages

src/Diagnostics.zig
Updated in https://github.com/ziglang/zig/commit/008b0ec5e58fc7e31f3b989868a7d1ea4df3f41d
=> Zig update: remove Mutex.Held

src/Parser.zig, test/cases/strings.c
Fix u21 overflow, check for surrogate codepoints, allow backtick to use UCN
=> Universal character names fixes

src/Parser.zig, test/cases/initializers.c
Only incomplete arrays can be initialized
Fixes #93, Fixes #98
=> Parser: don't allow initialization of most incomplete types

src/Preprocessor.zig, test/cases/macro unbalanced parens call.c
Nested expansions with unbalanced parentheses at the callsite could cause
start_idx to exceed end_idx; check for this and expand the buffer if
necessary.
Fixes #95
=> Preprocessor: start_idx can exceed end_idx in nextBufToken

src/Type.zig, test/cases/attributes.c
Render them as the underlying type
Fixes #102
=> Type: Handle attributed types in Builder.Specifier.str

src/Compilation.zig, src/Diagnostics.zig, src/Preprocessor.zig, src/Source.zig, src/main.zig, test/cases/latin1.c, test/runner.zig
Currently this just scans the whole file up-front to ensure that it is
utf-8 encoded. The scan is performed in preprocessor even though addSource
seems like a more natural fit because returning an error from that function
invalidates the source and path buffers which are needed for error messages.
Subsequent tokenizer enhancements will be needed for consuming unicode
codepoints instead of bytes (e.g. for identifiers); at that time the extra
scan can be removed and tokenizer.next() can either return an error or a special
token to indicate invalid utf8
=> Source: require source files to be utf-8 encoded

src/Compilation.zig
They are not legal on any system I know of, and trying to open such a path
can trigger an assert in the Zig stdlib
Fixes #106
=> Compilation: check for embedded null in include paths

test/fuzz/fuzz_lib.zig
Overlooked this since it's not added from a file
=> Fuzzer: check for utf-8 validity of input buffer

src/Parser.zig, test/cases/zero length multidimensional array.c
=> Parser: fix divide by zero on zero-length multidimensional arrays

src/Parser.zig, test/cases/call.c
void arguments handled separately
Fixes #130
=> Parser: Prevent call expression with incomplete-size argument

src/Compilation.zig, src/Diagnostics.zig, src/LangOpts.zig, src/Parser.zig, src/Preprocessor.zig, src/pragmas/gcc.zig, src/pragmas/once.zig, test/cases/adjust diagnostic levels.c, test/cases/functions.c, test/cases/return.c, test/cases/sizeof alignof.c, test/cases/static assert messages.c
A long overdue quality of life improvement to the diagnostics system so that you only have to modify one plave to add a new error instead of 4-5 spread accross many files.
Closes #81.
=> Make diagnostics declarative

src/Parser.zig, src/Type.zig, test/cases/attributes.c
Fixes #140
I manually verified that the provided test case matches clang's behavior (`__clang_max_align_nonce1` gets an `__aligned__(8)` attribute, `nonce2` gets `__aligned__(8)` and `packed`, `nonce3` gets `__aligned__(8)`, and `__clang_max_align_nonce2` gets `__aligned__(8)`). I don't have any good ideas of how to test this though - any thoughts?
=> Parser: parse attributes at end of record field decls

src/Preprocessor.zig, test/cases/comment after define.c
As it turns out, comment after simple #define (i.e the one without any value or function) causes it to skip the newline present in the current line and instead makes it to read till the eol of next line.
Example, the following snippet gives unexpected results:
```c
#define Y // test
#if 0
#endif  
Y;
```
arocc -E: (with error: ``error: #endif without #if``)
```c
#if 0;
```
with this PR: (which matches gcc and clang results)
```c
;
```
Possible reason:
``.whitespace => first = tokenizer.next()`` skips away the whitespace and then ``token_buf.append(first)`` appends the newline without checking.
=> Preprocessor: Fix comment after simple #define causing it to skip newline

src/Diagnostics.zig, src/LangOpts.zig, src/Parser.zig, src/Tokenizer.zig, src/main.zig, test/cases/dollars in identifiers.c
Also adds the related warnings -W(no-)dollar-in-identifier-extension
Closes #132
=> Add -fdollars-in-identifiers and -fno-dollars-in-identifiers option

src/Compilation.zig, src/Diagnostics.zig, src/Parser.zig, src/Preprocessor.zig, src/Tree.zig, src/main.zig, src/pragmas/gcc.zig, src/pragmas/once.zig, test/cases/generated location.c, test/cases/macro backtrace.c, test/cases/pragma in macro middle.c, test/cases/pragma in macro start.c, test/cases/preprocessor binary operators.c, test/runner.zig
This changes the order in which macro backtrace appears in diagnostics from the current which matches GCC to the reverse which maches clang and in my opinion makes more sense. It also adds a limit to how many backtrace notes are shown by default also matching clang.
Should unblock #157
=> Reverse order of macro backtrace, make generated behave more like other sources

src/Compilation.zig, src/Diagnostics.zig, src/InitList.zig, src/Parser.zig, src/Preprocessor.zig, src/Tree.zig, src/Type.zig, src/main.zig, src/object/Elf.zig, src/pragmas/gcc.zig, src/pragmas/once.zig, test/fuzz/fuzz_lib.zig, test/runner.zig
Allocators are now passed by value instead of reference.
See https://github.com/ziglang/zig/pull/10055
Closes #163
=> Zig stdlib: update Allocator interface

src/Tokenizer.zig
Prevents a `'\x7F'` character from triggering an assert
=> Tokenizer: CharInfo functions expect codepoint > 0x7F

src/Diagnostics.zig, src/pragmas/gcc.zig, test/cases/unknown GCC pragmas.c
An attempt to fix #166 
This creates two different warning messages for both cases mentioned here. But controlling option is only made available for the second (diagnostics case) following clang's style.
=> Pragma: improve misleading warning messages

src/Parser.zig, test/cases/initializers.c
Note: this fixes the crash in #170 but not the issue causing `const int` variable value to not be available.
=> Parser: issue an error for unavailable designated init indices.

test/README.MD, test/docker/fuzz/Dockerfile
This way the Dockerfile won't have to be updated every time there is a
breaking change in Zig.
=> Fuzzer: Use Dockerfile args for zig version and signature

src/Parser.zig, test/cases/unavailable results.c
=> Parser: treat non-integer casts and address-of operations as unavailable

src/Type.zig, test/cases/imaginary constants.c, test/cases/invalid types.c
With this PR an extra `warning: type specifier missing, defaults to 'int'`
warning is generated; but once complex integers are supported it will go
away
Fixes #190
=> Type: allow `_Complex` to combine with `long`

src/Parser.zig, test/cases/return.c
If a function is declared as returning a function it's already a syntax error,
so let it return whatever value it wants.
=> Parser: fix crash when returning value from invalid function

src/Diagnostics.zig, src/Parser.zig, src/Preprocessor.zig, src/Type.zig, src/pragmas/gcc.zig, src/pragmas/message.zig, test/cases/invalid types.c
The error message is not good but this one will also go away once complex
integer types are supported
=> Type: don't crash on `_Complex long int`

src/Parser.zig, test/cases/attributes.c
Invalid attributes are not added to `attr_buf`, so a different strategy
is needed to check whether any attributes were parsed.
=> Parser: handle the possibility of invalid attribute at eof

src/Diagnostics.zig, src/Parser.zig, test/cases/binary literal.c
Adds warning for binary integer literal which was one of the motivation behind #59
=> Diagnostics: Add warning for GNU binary literal extension in pedantic mode

src/Preprocessor.zig, test/cases/macro unbalanced parens call.c
=> Preprocessor: ensure expansion_locs of trimmed tokens are freed.

src/Parser.zig, test/cases/typeof.c
Prevents access of inactive union field when attempting to use a
typeof-type or -expression as an incomplete array initializer.
=> Parser: use arrayLen to get array initializer length

src/Parser.zig, src/Type.zig, test/cases/attributes.c
=> Parser: ensure attributed specifier is not lost for old-style functions

src/Diagnostics.zig, src/Parser.zig, src/Type.zig, test/cases/casts.c
Fixes #228
Print correct type in an error message about casting
=> Parser: handle casting of string literals

src/Compilation.zig
Previously any input error would be treated as a legitimate end of stream;
instead specifically check for EndOfStream and bubble all other errors up
to the caller
=> Compilation: handle non-EOF input errors properly

src/Parser.zig, test/cases/binary expressions.c
=> Parser: set results to unavailable if used as part of an invalid binary expression

src/Preprocessor.zig, test/cases/nested unterminated macro.c
Nested unterminated macro expansions could underflow `moving_end_idx`
Also addresses a memory leak encountered when eof occurs during
macro argument collection.
Fixes #247
=> Preprocessor: Handle potential integer underflow in macro expansion

src/Diagnostics.zig, src/Parser.zig, test/cases/empty records.c, test/cases/initializers.c
Also adds a warning for different empty-record sizes in C vs C++
=> Fix crash for empty unions with aggregate initializers

src/Parser.zig, test/cases/casts.c
Values can be implicitly cast to void if the other branch of a
conditional operator is void.
Fixes #252
=> Tree: don't try to print values of type void

src/Diagnostics.zig, src/Parser.zig, test/cases/bitfields.c, test/cases/const decl folding.c
Add supports for folding const int decls in certain situations where GCC/clang allow them.
=> Const decl folding

src/Compilation.zig
Refactor addSourceFromReader to take a size argument instead of a
pre-allocated buffer. This makes it easier to clean up resources in
the case of a memory allocation failure. Adds a test to ensure that
an allocation failure in addSourceFromReader will not leak memory.
=> Compilation: refactor addSourceFromReader

src/Parser.zig
=> Parser: Do not allow incomplete-size fields in anonymous records.

build.zig, src/Parser.zig, src/Preprocessor.zig, src/Tree.zig, test/runner.zig
Initial support for #74
Run with `zig build test -Dtest-all-allocation-failures=true` (currently finds some leaks)
Eventually `checkAllAllocationFailures` should be used per test-case, but for now was easier to just apply it to the whole test suite
=> Test all allocation failures

src/Compilation.zig, src/Preprocessor.zig, src/Source.zig
Store invalid UTF-8 locations in a hash map in Compilation, instead of directly
in Source. This incurs a fixed cost of 16 bytes per Compilation to store the
hash map, but saves 12 bytes per Source which is valid UTF-8. Since there will
generally be many Sources, and invalid UTF-8 is an uncommon and fatal error,
this should usually result in less memory usage.
=> Source: move invalid-utf8 location storage into Compilation

src/Parser.zig, src/SymbolStack.zig, test/cases/containers.c, test/cases/enumerator constants.c
Additionally fixes an issue where the first enumeration constant defaulted
to 1 instead of 0.
Closes #286
=> Parser: allow enumeration constants to be used as constexpr's

build.zig, src/Attribute.zig, src/Compilation.zig
1. `std.build.Pkg.path` renamed to `std.build.Pkg.source`
2. std.math.cast now returns an optional instead of error
=> Stdlib updates

src/Parser.zig, test/cases/attributes.c
=> Parser: ensure that attributes after a record's closing rbrace aren't ignored

src/Parser.zig, test/cases/attributes.c, test/cases/enum attributes.c
1. Ensure trailing attributes after an `enum` r_brace are attached to the enum
2. Fetch the attributed type when a struct/union/enum is referenced by name
=> Attribute fixes

src/Compilation.zig, src/Diagnostics.zig, src/Parser.zig, src/Type.zig, test/cases/enumerator constants.c
According to the C standard they should fit in an int, but gcc and clang allow them to use a larger type.
=> Enums: issue a warning if enumerator constants too small/large

src/Compilation.zig, src/Diagnostics.zig, src/Preprocessor.zig, src/Tokenizer.zig, test/cases/include/my_include.h, test/cases/include/next/my_include.h, test/cases/include/next/other.h, test/cases/include/other.h, test/cases/include_next.c, test/runner.zig
This is a very basic implementation of `#include_next` that just uses exact string matches to advance the iterator past the directory of the current file.
The clang code for looking up includes has a lot going on: https://github.com/llvm/llvm-project/blob/264c09b732ab61936a499f133abdfc67df422a86/clang/lib/Lex/HeaderSearch.cpp#L836= which could be a fruitful source of ideas of how to improve things.
Not sure if these should be separate issues, but possible enhancements include: caching so that we're not repeatedly looking up nonexistent files, Apple Framework support, `O(1)` advancement of the `include_next` iterator, MSVC-style "include stacks", tracking whether the current file was included by quoted include / angled include / absolute path
=> Basic implementation of #include_next

include/stddef.h, src/Codegen.zig, src/Parser.zig, src/SymbolStack.zig, src/Tree.zig, test/cases/containers.c
The only situation I found where this happens is if immediately followed by a semicolon but I've been wrong before.
Closes #306
=> Parser: improve handling of record & enum forward declarations

.gitattributes, src/Parser.zig, src/Tree.zig, src/codegen/x86_64.zig, test/cases/ast/cast kinds.c, test/cases/ast/types.c, test/cases/cast kinds.c, test/runner.zig
Briefly discussed here: https://github.com/Vexu/arocc/pull/232#issuecomment-1030530859
If you like this approach I can fill out the `fromExplicitCast` function.
=> Tree: store cast kind as part of implicit/explicit cast nodes

src/Compilation.zig, src/Diagnostics.zig, src/Parser.zig, src/Type.zig, src/Value.zig, test/cases/ast/types.c, test/cases/enum fixed.c, test/cases/enum overflow.c, test/cases/enum sizes linux.c, test/cases/enum sizes windows.c, test/cases/enum sizes.c, test/cases/types.c
Calculate enum sizes, accounting for packed attributes and overflow
=> Enum sizes

src/Compilation.zig, src/main.zig, test/runner.zig
With this change I'm able to parse the sqlite3 amalgamated source with no errors (just a bunch of spurious "unreachable code" warnings) on an x86_64 Ubuntu system without passing any additional command-line flags.
=> Add Linux multiarch include dir

build.zig, src/tracy.zig
This is just lifted from Zig's Tracy integration. Makes it easy to drop in 
```zig
const tracy = trace(@src());
defer tracy.end();
```
to any function you want to trace.
=> Build: add Tracy integration

src/Diagnostics.zig, src/Parser.zig, test/cases/old style flexible array.c, test/cases/zero length array.c
=> Parser: don't issue a bounds warning for trailing one-element array access

src/Tokenizer.zig, src/unicode.zig
Ignore all possible UTF8 decoding errors during tokenization, since
non-UTF8 data is already a fatal error that prevents tokenization
from happening.
Closes #333
Screenshots are from tracing `Tokenizer.next` when parsing the sqlite3 source code on x86_64 Linux.
Before:
After:
=> Tokenizer: optimize UTF8 decoding

src/Attribute.zig, src/Builtins.zig, src/Compilation.zig, src/Parser.zig, src/Preprocessor.zig, src/StringInterner.zig, src/SymbolStack.zig, src/Tree.zig, src/Type.zig, src/lib.zig, test/runner.zig
Initial pass at #315
If this approach looks good I can apply it to the other `[]const u8` fields in `Type.zig`.
One slightly annoying thing is juggling the `string_interner` in the test runner, to make sure it doesn't get de-inited. I could make the string interner not be owned by the Compilation, but I'm not sure that feels right either.
=> WIP: String interning for types

src/Compilation.zig, src/main.zig
Some target-specific question FNs needed for layout.
The most controversial is setting the compiler emulation based on the target. It sets the emulation to the compiler the target system is typically built with. So for example, Linux is built w/ gcc, so that's the compiler to emulate for linux targets. the `--emulate` flag overrides.
=> set default compiler, and other target queires

src/Preprocessor.zig, test/cases/guard defined outside header.c, test/cases/guard undef.c, test/cases/include/correct_guard.h, test/cases/include/incorrect_guard.h, test/cases/incorrect guard.c
We can skip preprocessing a file if it is entirely contained in
an #ifndef ... #endif guard and the guard macro is defined.
Closes #341
=> Preprocessor: check for include guards

src/Compilation.zig, src/Parser.zig, src/Type.zig
Add `TypeLayout` to `Record` and `FieldLayout` to `Field` in `Type.zig`
`TypeLayout` is probably too fat. I think I can cut it in half, but I'd like to finish msvc and MinGW layout emulation before doing that. It helps w/ diff-ing the rust code.
Removed `size` and `alignment` from `Record` as they are duplicative of `TypeLayout`
Changed `bits` in `Field` to be nullable, as 0 and unset mean different things to the layout code.
=> prep record struct for layout

src/Parser.zig, test/cases/sizeof variably modified types.c
=> Parser: don't error on sizeof VLAs and variably-modified types

src/Type.zig, test/cases/attributes.c
This is the last change needed for `record_layout.zig`.
I could put this in the PR w/ the layout code, but I wanted to draw your attention to it, as I'm not sure this is the proper way to handle these issues. There might be more of these types of exceptions in the future.
=> change logic in `Type.alignof()`

deps/zig/lib.zig, deps/zig/type.zig, src/Compilation.zig, src/Type.zig, test/cases/msp430 builtin types.c
Macros taken from here: https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/Targets/MSP430.cpp
Size, alignment, va_list, char signedness info: https://www.ti.com/lit/an/slaa534a/slaa534a.pdf (page 12)
The MSP430 compiler also has the concept of code models. Different code models can adjust the size
of function pointers, data pointers, size_t, and ptrdiff_t. We currently only support the small model.
Closes #346
=> Compilation: add MSP430 target-specific types and macros

src/Diagnostics.zig, src/Preprocessor.zig, src/Tokenizer.zig, test/cases/macro expansion to defined parsed.c, test/cases/macro expansion to defined.c
Since `defined` needs to look at its argument before expansion
happens, it needs to be special cased in expandMacroExhaustive.
It can't be a special function-like macro because that will cause
incorrect expansion outside of preprocessor expression contexts.
It can't be handled solely in `Preprocessor.expr` because the
argument will have been expanded by that point.
Closes #337
=> Preprocessor: handle macros which expand to `defined`

src/Preprocessor.zig, src/Tree.zig, test/cases/expanded/macro expansion disabled.c, test/cases/macro expansion disabled.c
The text of 6.10.3.4.2 is somewhat ambiguous:
These nonreplaced macro name preprocessing tokens are no longer available
for further replacement even if they are later (re)examined in contexts in
which that macro name preprocessing token would otherwise have been
replaced.
The immediately preceding text is describing the rule for not recursively
replacing a macro with itself if it appears in its own replacement list,
but a token is also "nonreplaced" if it is a function-like macro that is
not followed by a left parenthesis. GCC and clang both do not expand
a macro in this case during a rescan.
This rule only applies if a macro is nonexpanded in a replacement list;
it does not apply to argument pre-expansion.
Closes #339
=> Preprocessor: track nonreplaced function-like macros

src/Preprocessor.zig, test/cases/macro expansion to defined.c
We do not need to consume an extra token after handling `defined`
since the loop continue expression will do that for us.
Closes #383
=> Preprocessor: correctly handle parenthesis around `defined`

src/Attribute.zig, test/record_runner.zig
#332
If a typedef has attributes and so does decl it refers to, only take the attributes from the "top" typedef. 
This just ignores all attributes on the referred decl. That might not be correct. I can stip out just the aligned attribs if you think it's incorrect.
This fix allows 1K-ish tests to pass the layout tests, and reduces the number of tests that fail on all platforms from 4 to 1.
=> Fix for nested typedefs #332

src/Compilation.zig, src/Type.zig, src/record_layout.zig, test/record_runner.zig, test/records/0062_test.c
This was causing passing tests to show up as failed.
=> Layout tests: Disable `implicitly-unsigned-literal` warning

src/Parser.zig, test/cases/msvc zero size array.c
Previously, creating a variable of a type that contains a FAM errored due to a record field having incomplete size.
Closes #404
=> Parser: better support for flexible array members

deps/zig/type.zig, src/Value.zig, test/record_runner.zig
Fixes signed integer compare, and layout on avr/msp430 (clang and gcc disagree on `short` alignment on avr; GCC seems to be the compiler of record since clang's support is experimental https://llvm.org/doxygen/md_lib_Target_AVR_README.html) - should we try to emulate clang? 
https://godbolt.org/z/45Ezjzh8T
=> Layout fixes for avr/msp430

src/Diagnostics.zig, src/Parser.zig, test/cases/msvc flexible array in union.c, test/record_runner.zig
Previously we were defining MSVC and turning on MS extensions if the target OS was windows; instead we should only do that if we're emulating MSVC. This makes a bunch of mingw tests pass and a few UEFI ones not pass; net 81 expected failures removed.
=> Layout tests: don't skip mingw tests

src/Diagnostics.zig, src/Parser.zig, src/Type.zig, test/cases/#pragma pack clang.c, test/cases/#pragma pack gcc.c, test/cases/#pragma pack msvc.c, test/cases/sizeof alignof.c
Disallow _Alignof (and _Alignas) for incomplete records and enums
Handle differences in `#pragma pack` behavior when it changes mid-record.
=> Small fixes for #pragma pack and _Alignof

include/stdarg.h, include/stdatomic.h, include/stdbool.h, include/stddef.h, src/LangOpts.zig, test/cases/c23 defines.c, test/cases/stdarg.c
The final value is subject to change but this should let us start defining feature test macros as necessary for new c23 keywords and header changes
=> Langopts: Set __STDC_VERSION__ for c2x (C23)

include/stdalign.h, include/stdbool.h, src/Diagnostics.zig, src/Parser.zig, src/Preprocessor.zig, src/Tokenizer.zig, test/cases/c23 keywords.c, test/cases/keyword hidden by macro.c
Note: this is based on #431, I can rebase or edit as necessary 
Add `alignas`, `alignof`, `bool`, `static_assert`, and `thread_local` as keywords. `true` and `false` will be done separately because they add a new syntax term `predefined constant` that can also be used to implement `nullptr`; plus they'll need a bit more preprocessor support to ensure `true` works as intended.
=> C23 keywords

include/stdbool.h, src/CodeGen.zig, src/Compilation.zig, src/Parser.zig, src/Preprocessor.zig, src/Tokenizer.zig, src/Tree.zig, src/Type.zig, src/Value.zig, test/cases/ast/c23 true false ast.c, test/cases/c23 keywords.c, test/cases/c23 true false ast.c, test/cases/constexpr.c, test/runner.zig
I removed `__STDC_VERSION_BOOL_H__` because it looks like it's not defined in the latest draft I was able to find. I also removed `__bool_true_false_are_defined` for C23 because in C23 stdbool.h "provides no content".
=> add support for c23 true/false keywords

src/Attribute.zig, src/Parser.zig, src/Type.zig, test/cases/ast/vectors.c, test/cases/extended identifiers c11.c
The primary purpose of this is to allow us to parse more subexpressions when an incomplete operation is encountered and to reduce invalid error messages as a result of invalid operations having a valid type.
Like NaN all operations on `invalid` should either result in itself or false.
=> Type: add poison type `invalid`

src/Diagnostics.zig, src/Parser.zig, src/Type.zig, test/cases/sizeof alignof.c
1. Issue a warning for sizeof/alignof `void`
2. Issue a warning for sizeof(decayed array)
3. Treat sizeof(incomplete_size_type) or alignof(non_alignable_type) as parse errors. This matches clang's behavior and lets us remove some hacky error-suppression code in static_assert handling
This is part of the groundwork for some other static_assert changes I'll be making (clang trunk no longer requires that static_assert expressions be *integer* constants: https://godbolt.org/z/oafvqTEjx) which is itself part of the work for adding C23 nullptr support.
=> Parser: improve sizeof/alignof handling and errors

src/Diagnostics.zig, src/Parser.zig, test/cases/const decl folding.c
This matches the behavior on clang trunk - question - should we only do this when emulating clang? Would be easy enough to swap out the call to `p.constExpr` in `staticAssert` for `p.integerConstExpr` depending on compiler.
=> Update static assert to allow any constant expression

include/stddef.h, src/Attribute.zig, src/CodeGen.zig, src/Diagnostics.zig, src/Interner.zig, src/Parser.zig, src/Tokenizer.zig, src/Tree.zig, src/Type.zig, src/Value.zig, test/cases/nullptr.c
I tried to follow clang's example; including when their behavior seems to go against the draft - e.g. it's an error in clang to assign `nullptr` to a bool without a cast, but the draft seems to indicate that is ok and should evaluate to `false`.
I left the IR unimplemented because I'm not sure if you want to add a new constant type for `null` - but it's supposed to have the `size and alignment of nullptr_t is the same as for a pointer to character type. An object representation of the value nullptr is the same as the object representation of a null pointer value of type void*`. Reading from a variable of type `nullptr_t` always produces the value that would be produced by reading from a null pointer of type `void *`.
I'm not saving values of `nullptr_t` into `value_map` since variables of …
=> Add C23 `nullptr` support to frontend

include/stddef.h, src/Builtins.zig, test/cases/unreachable.c
Note: the `Type` returned by `Builtin.get` for `__builtin_unreachable` is currently incorrect since it doesn't include the `noreturn` attribute - do you want me to add that or will that be handled in by grabbing the associated `Builtin.Attributes` object?
=> Builtin: Add C23 unreachable() support to frontend

src/Attribute.zig, src/Tree.zig, test/record_runner.zig
Rename the `field_type` field of enum meta to `type`
Remove an incorrect discarded `if` capture.
=> Small zig updates

src/Parser.zig, src/Type.zig
These parameters don't seem to actually be used (just passed along to recursive calls to the same function). Not sure if they're there as a placeholder for future use or just a remnant of some earlier code
=> Type: remove unused parameters to `combine`

src/Parser.zig, test/cases/compound literals.c
The C grammar treats them as suffix expressions instead of cast expressions
Closes #451
=> Parser: Treat compound literals as a suffix expression

src/Compilation.zig, src/Diagnostics.zig, src/Driver.zig, src/LangOpts.zig, src/Parser.zig, src/SymbolStack.zig, src/Tree.zig, src/Type.zig, src/target.zig, test/cases/allow fp16 parameter.c, test/cases/ast/float eval method.c, test/cases/ast/native half type.c, test/cases/ast/promotion edge cases.c, test/cases/float eval method.c, test/cases/fp16 parameter aarch64.c, test/cases/fp16 parameter.c, test/cases/native half type.c, test/cases/promotion edge cases.c
Promote char/short to int before converting to floating point if use in FP arithmetic.
Promote bitfields to int if int is large enough to contain all the values (keeping some gcc/clang errata)
Promote __fp16 to float for arithmetic, and disallow it as a parameter type
Use fp_eval_method setting to promote intermediate floating point results
Avoid extra implicit cast when converting between real and complex of same underlying type in an init expression.
=> Fix some promotion edge cases

src/Parser.zig, src/Tokenizer.zig, src/Tree.zig, src/Type.zig, src/number_affixes.zig, test/cases/_Float16.c, test/cases/ast/_Float16.c
Note: This includes the changes in the `promotions` branch.
Adds support for the `_Float16` type, and floating point literals of that type (`f16` suffix).
Removes `_Complex __fp16` since clang and gcc do not support that type.
=> Parser: Add `_Float16` support

include/limits.h
Forgot to undefine these in the first PR. We know the sizes of types so it's ok to override the system's limits.h values, if any.
Closes #461
=> limits.h: undefine all macros which we define

src/Compilation.zig, src/Diagnostics.zig, src/Parser.zig, src/Type.zig, src/number_affixes.zig, test/cases/_BitInt.c
Currently only supports 64-bit or smaller literals.  We'll need a way to handle larger values - any thoughts on that? 128-bit `int` field in `Value.data`? make `Value.data.int` a union w/ 64 bit int or pointer to bigint?
=> Add C23 _BitInt suffix for integer literals

src/Parser.zig, src/Type.zig, src/Value.zig, test/cases/integer conversions 32bit.c, test/cases/integer conversions.c
Fixes #459 as well as some edge cases on 32-bit systems (e.g. `long` + `unsigned` should be `unsigned long` if `long` and `unsigned` are the same size) and with complex integers.
=> Improve integer conversion

build.zig
Not sure if this is the right fix because I don't actually remember what `expected_term` used to be, but since we were setting it to null maybe it's not needed? With latest Zig it complains `no field named 'expected_term' in struct 'Build.RunStep'`
=> build: Zig build system update - remove RunStep.expected_term usage

src/Parser.zig, src/Tokenizer.zig, src/Tree.zig, test/cases/u8 character constant.c, test/cases/wide character constants.c
Add support for C23 u8 character constants
disallow multibyte constants for character literals and u8 character literals (this matches the behavior of clang where e.g. `'\xA3'` is allowed but `'£'` is not, even though `£` is unicode code point 0xA3; because `£` is encoded as `0xC2A3`, which is too large for a char; clang does this even though the type of the char literal is indeed `int`.)
Fix an issue where multi-character character constants received an incorrect value due to multiplying by e.g. 0xFF instead of 0x100
=> u8 char literals and some other char improvements

src/Compilation.zig, src/Driver.zig, src/LangOpts.zig, src/Type.zig, test/cases/signed char.c, test/cases/unsigned char.c
Adds support for the `-fsigned-char` / `-funsigned-char` family of command line flags
=> Allow overriding char signedness

src/Driver.zig, src/LangOpts.zig, src/Parser.zig, test/cases/c17 char8_t enabled.c, test/cases/c17 char8_t.c, test/cases/c2x char8_t disabled.c, test/cases/c2x char8_t.c, test/cases/generic.c
Adds `char8_t` as a builtin typedef for `unsigned char` in C23 or if `-fchar8_t` is passed. Unlike C++ it's just a typedef and not a distinct incompatible type.
If `char8_t` is enabled, `u8` string literals have type `char8_t[N]` instead of `char[N]`, but can still be used to initialize arrays of `char` or `signed char`.
Fixes a bug with `_Generic` where the controlling expression was not undergoing array decay.
=> Add C23 char8_t

src/Compilation.zig, src/Parser.zig, src/Value.zig, src/target.zig, test/cases/#if constant expression.c, test/cases/intmax_t.c, test/cases/signed char.c, test/cases/unsigned char.c
The preprocessor is supposed to do all math with `intmax_t` or `uintmax_t` instead of using C promotion rules. This adds support for determining the `intmax_t` type for different platforms + a fixes a few other bugs I found while working on that.
=> Use intmax_t/uintmax_t in preprocessor

src/lib.zig
Export Type.zig from the library.
I'm using arocc as a  library for my attempt at translate-c here
https://github.com/TwoClocks/aro-translate-c
=> export Type.zig from library

src/Attribute.zig, src/Diagnostics.zig, src/Parser.zig, src/Tokenizer.zig, src/Type.zig, test/cases/__auto_type.c
This implements GCC-style `__auto_type` as a type specifier. Clang implements it as C++ `auto` which is more powerful in that it allows multiple declarators and non-simple declarators. C23 auto is based on the GCC variant.
Closes #173
=> Parser: implement __auto_type

src/Diagnostics.zig, src/Parser.zig, test/cases/containers.c
=> Parser: allow omitting the semicolon after the last declarator in a record

src/Diagnostics.zig, src/Parser.zig, src/Tree.zig, test/cases/containers.c, test/cases/invalid types.c, test/cases/tentative definitions.c
Allow top-level definitions of symbols which have incomplete record or enum types, and only issue an error if the type is never completed.
=> Parser: allow tentative top-level records and enums

deps/zig/codegen/x86_64.zig, src/Attribute.zig, src/Builtins.zig, src/CodeGen.zig, src/Codegen_legacy.zig, src/Compilation.zig, src/Interner.zig, src/Ir.zig, src/LangOpts.zig, src/Parser.zig, src/Preprocessor.zig, src/StringInterner.zig, src/Tree.zig, src/Type.zig, src/Value.zig, src/codegen/x86_64.zig, src/main.zig, src/object/Elf.zig, test/runner.zig
e.g. `@intToEnum` -> `@enumToInt`
=> Zig update: builtin rename: xToY -> yFromX

src/Diagnostics.zig, src/Parser.zig, src/Type.zig, test/cases/assignment.c, test/cases/call.c, test/cases/initializers.c, test/cases/return.c
Note: With these changes, `ReleaseFast` and `ReleaseSmall` fail to build on Linux, see https://github.com/Vexu/arocc/issues/490
Fixes non-ints/pointers coercing to `void *`
Allows pointers to different child types to coerce to each other with a warning instead of error
Adds a special warning for coercing between pointers where only the signedness of the child type differs
=> Improve pointer coercion

build.zig
Exposes `src/lib.zig` as the `aro` module.
=> Build: make aro module public

src/Driver.zig
Fix for #497 - always dupe temporary linker filenames (anything that is not a `.o` or `.obj` file specified directly in the command line) and free during driver deinit.
Small driver cleanup - fix an error message typo + add `--assemble` and `--compile` command line options
=> Driver fixes

src/Codegen_legacy.zig, src/Diagnostics.zig, src/Driver.zig, src/LangOpts.zig, src/Parser.zig, src/Tokenizer.zig, src/Tree.zig, test/cases/gnu inline assembly statements.c, test/cases/no inline asm.c
Primary thing here is adding support for GNU inline assembly statements. Currently it just parses the statement, no attempt is made to validate it. There's also the question of how it should be added to the AST - any thought about how to structure that? There's a lot of data - the assembly template string, `volatile` flag, inputs, output, and label expressions, constraints, clobbers...
=> Assembly statement parsing 

.github/workflows/ci.yml, src/Driver.zig
If fast_exit is enabled (non-debug build) then processSource can invoke the linker
Fixes #501
=> Driver: handle different debug/release error sets for processSource

.github/workflows/ci.yml, build.zig, src/Attribute.zig, src/Compilation.zig
Updates build.zig to allow running the integration and record layout tests with the specified optimization level. Running them this way uncovered an issue in `Attribute.zig` where attribute arg structs were being incorrectly initialized. Updates the CI action to also run the tests in ReleaseFast mode.
=> Allow setting the build mode for tests

src/Attribute.zig
I had forgotten `mem.zeroInit` exists but this seems like a better solution than sprinkling `undefined` everywhere.
=> Attribute: use zeroInit instead initializing with undefined

.github/workflows/ci.yml
Setting `fail-fast` to false can allow the jobs for the other OSes to continue even when the CI fails for 1 OS: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures
Not sure if this is desired - feel free to close this if this isn't.
=> ci: use `fail-fast: false` for matrix

src/Attribute.zig, src/Preprocessor.zig, src/Tokenizer.zig, src/target.zig, test/cases/declspec.c, test/cases/no declspec.c
closes #419 
CI seems to be failing, not sure if it's related to [this](https://github.com/Vexu/arocc/pull/510#issuecomment-1738617220)?
=> feat: implement `__has_declspec_attribute`

src/Compilation.zig, src/Diagnostics.zig, src/Driver.zig, src/Preprocessor.zig, src/Tokenizer.zig, src/Tree.zig, test/cases/include/ms-ext/include other.h, test/cases/ms-extensions.c, test/runner.zig
=> Compilation: support backslashes in filenames when ms-extensions are enabled

src/Compilation.zig
Instead of reading one byte at a time via a reader, just read the whole thing into a []u8 and operate on it from there.
Not sure why I did it one byte at a time via a reader originally but this way is faster:
parsing sqlite3.c, master branch
```
real	0m0.358s
user	0m0.342s
```
parsing sqlite3.c, this branch,
```
real	0m0.333s
user	0m0.304s
```
Tests in ReleaseFast, master branch
```
real	0m3.036s
user	0m23.240s
```
Tests in ReleaseFast, this branch:
```
real	0m2.733s
user	0m20.778s
```
=> Compilation: read entire source into a buffer before processing it

src/CharLiteral.zig, src/Compilation.zig, src/Diagnostics.zig, src/Parser.zig, src/Tokenizer.zig, test/cases/strings.c, test/cases/wide character constants.c
Summary of changes:
1) Move char literal validation to the parser instead of tokenizer. This means that ill-formed char literals can be diagnosed as such, instead of just being treated as invalid tokens.
2) Allow arbitrarily-long hex escapes. Previously they were limited to a 2-digit maximum
3) Use correct size for char literals (`char16_t` aka `uint_least16_t` for utf16 literals, `char32_t` aka `uint_least32_t` for utf32 literals; previously these unconditionally used `unsigned short` and `unsigned long`)
4) Proper range checking for numeric escapes (e.g. `L'\777'` is valid because `511` fits into a wide character)
5) Added `\E` escape as well as `'\('`, `'\{'`, `'\['`, and `'\%'` (non-standard GNU escapes)
There are some redundancies with how string literals are handled; my plan if …
=> Improve character literal handling

src/Parser.zig, src/SymbolStack.zig, src/Type.zig, test/cases/invalid types.c, test/cases/redefinitions.c, test/cases/tentative array.c
I tried to figure these out by reading the standard but it's pretty dry. 
Functions in C11 6.7.6.3.15 (too long to paste)
Arrays in C11 6.7.6.2.6: "For two array types to be compatible, both shall have compatible element types, and if both size specifiers are present, and are integer constant expressions, then both size specifiers shall have the same constant value"
Briefly,
1) Arrays with same child type are compatible if at least one array is incomplete or if they have the same constant integer length
2) Functions must both have or both not have ellipses to be compatible
3) A function with no prototype is compatible with a function with a parameter list if none of the named parameter types undergo default argument promotion and the return type is compatible
=> Type: improve type equality checking

deps/zig/codegen/x86_64.zig, src/Compilation.zig, src/Diagnostics.zig, src/object/Elf.zig, src/target.zig
The C backend currently can't handle them. This is the only thing preventing the CBE from being able to produce valid C code from aro (I have not verified that the produced code actually works, however). 
If the produced code works as expected, this will unblock https://github.com/ziglang/zig/pull/17771
Does `Relocation` even need to be packed? It looks like we aren't bitcasting it, and it's 32 bytes regardless of whether it's packed or not (the bitsize is 184 when packed vs 256 when not packed, but if we're only using it in `ArrayListUnmanaged` then that shouldn't matter, right?)
`Options` goes from 64 bytes -> 104 bytes when not packed, but we only have 1 of those per Compilation.
=> Zig workaround: don't use packed structs larger than 128 bits.

src/Parser.zig, test/cases/functions.c
resolve #351
When parsing old style parameter declarations, declarator kind was not initialized as param but as normal, that generate an error for K&R style function definition when using static.
Added a test in cases/functions.c
=> Parser: set kind to param in old style parameter declarations

test/record_runner.zig, test/runner.zig
When doing a build test with the option --cache-dir using a separated path from the repo directory it result in an AroIncludeNotFound error, that happened because the runner called defineSystemIncludes with the path from the executable generated in the cache-dir and can't find the root of the repository and the include directory:
```
error: AroIncludeNotFound
error: AroIncludeNotFound
Panicked during a panic. Aborting.
/tmp/arocc/test/runner.zig:174:5: 0x3d96f8 in main (test-runner)
try initial_comp.defineSystemIncludes(self_exe_dir);
^
run test-runner: error: the following command exited with error code 1:
/tmp/build/o/b8fcd66fba7ad45a2bc6547a44f01508/test-runner /tmp/arocc/test/cases /home/daniel/programas/zig/zig 
run record-runner: error: the following command terminated unexpectedly: …
```
=> Test_runner: change self_exe_dir for test_dir

src/Parser.zig, test/cases/initializers.c
resolve #537
coerceArrayInit was not used in findScalarInitializer, using only a type equality, so instead of coercing the string it only checked if the type was equal, and because the length was different the array was rejected and istead used implicit conversion to char from pointer.
=> Parser: Coerce array members properly from strings

src/Tokenizer.zig, test/cases/numbers.c
Previously we were transitioning back to `.pp_num`, which meant that a subsequent minus sign (-) would be treated as an operator instead of part of the exponent if we got to `.pp_num_exponent` via 'e' or 'E' as hex digits instead of exponent indicators.
=> Tokenizer: stay in `.pp_num_exponent` state if we encounter 'p' or 'P'

src/aro/Driver.zig
=> Properly exit on error when `-E` (preprocess only) is set

build/GenerateDef.zig, deps/zig/arch/x86_64/Disassembler.zig, deps/zig/arch/x86_64/Lower.zig, deps/zig/arch/x86_64/encoder.zig, src/aro/Compilation.zig, src/aro/Parser.zig, src/aro/Preprocessor.zig, src/aro/Type.zig, src/aro/Value.zig, src/aro/pragmas/message.zig, src/backend/Object/Elf.zig, test/fuzz/fuzz_lib.zig, test/record_runner.zig, test/runner.zig
These were noticed downstream, since I am in the process of implementing an error for uses of 'var' when one provably could have used 'const'.
Note that the changes in 'deps' are not currently in the Zig codebase, but will be a part of an imminent PR there. I thought it made sense to make them now to avoid having to sync this code once the new error is introduced.
=> all: fix unnecessary uses of 'var'

src/aro/Parser.zig, src/aro/Type.zig, test/cases/ast/decayed attributed array.c, test/cases/decayed attributed array.c, test/cases/typeof.c
It's not pretty but I view this as a stopgap measure until the Type system is rewritten. My main motivation is that it's currently not possible to use aligned arrays, which I suspect are fairly common in large real-world projects.
=> Type: use a separate flag for decayed arrays instead of encoding it in the specifier

build.zig, build/ZigLibDir.zig, src/aro/Parser.zig, test/README.MD, test/docker/fuzz/Dockerfile, test/fuzz/fuzz_lib.zig
I was having trouble getting the old fuzzing instructions to work (having to do with opaque pointers in llvm; by default AFL uses clang 14 which defaults to typed pointers but I didn't investigate too deeply).
The new method just compiles aro to C and then runs that through `afl-clang-lto`. It seems to work pretty well - I'm just not sure if I'm handling `compiler-rt` and the `zig.h` location in the best way.
=> Update fuzz step and instructions and fix a bug it caught

include/stdatomic.h, src/aro/Builtins/Builtin.def, src/aro/Compilation.zig, src/aro/Parser.zig, test/cases/atomic builtins.c
I believe this should bring us up to speed on frontend support for atomics. Still no checking of arguments for the atomic functions but I think now we should be able to accept all well-formed programs that use these functions.
=> Parser: Add frontend support for C11 atomics

README.md
run step is no longer in `build.zig`, so the README example no longer works. We just use `zig run` instead.
=> update README with zig run

src/aro/Type.zig, test/cases/functions.c, test/cases/redefinitions.c
1. Check that param counts match before looping over them
2. Allow 0-argument new-style/old-style redefinition
=> Function type comparison tweaks

src/aro/Compilation.zig
Prevents a crash caused by embedded NUL bytes
=> Compilation: check for embedded null bytes in path for has_include

src/aro/Builtins.zig
With this + #591 + #592 I'm able to parse `zig2.c` on my linux system without using an external preprocessor 🤯
Current numbers for reference, looks like we need to cut back on memory usage a bit but speed is looking good :)
```
Benchmark 1 (6 runs): clang -std=c11 -Ilib -fsyntax-only build/zig2.c
measurement          mean ± σ            min … max           outliers         delta
wall_time          10.9s  ± 24.4ms    10.9s  … 10.9s           0 ( 0%)        0%
peak_rss           1.00GB ± 37.0KB    1.00GB … 1.00GB          0 ( 0%)        0%
cpu_cycles         44.3G  ± 99.6M     44.1G  … 44.4G           0 ( 0%)        0%
instructions       72.1G  ±  129M     72.0G  … 72.3G           0 ( 0%)        0%
cache_references    204M  ± 3.58M      201M  …  210M           0 ( 0%)        0%
cache_misses …
```
=> Builtins: handle _Float16 type specifier

src/aro/Compilation.zig, src/aro/target.zig, test/cases/wide character constants.c
These are used by the host `stdatomic.h` on my system.
=> Compilation: define char types and sig_atomic size

src/aro/Preprocessor.zig
Line numbers are 1-indexed, not 0-indexed. Before this commit, include_start/include_resume tokens were being added with a mix of 1-indexed and 0-indexed line numbers. After this commit, all line numbers are 1-indexed.
Closes #604
I would have added test cases, but there's nothing in place for testing linemarkers (if I add a test case, the file paths in the line markers end up as absolute). For example, this test case:
```c
//aro-args -E -fuse-line-directives
this is line 2
this is line 10
```
Expects this output:
```c
#line 2 "/home/ryan/Programming/zig/arocc/test/cases/linemarkers.c"
this is line 2
#line 10 "/home/ryan/Programming/zig/arocc/test/cases/linemarkers.c"
this is line 10
```
Let me know if you have an idea of how to add test cases for this. 
---
Fixes all the reproductions of …
=> Fix incorrect line numbers in linemarkers

build.zig, build/GenerateDef.zig, src/aro/Driver.zig, src/aro/Value.zig, src/aro/toolchains/Linux.zig
This gets aro compiling again after https://github.com/ziglang/zig/pull/18160. This is not thoroughly tested, so double check that all the changes make sense.
Some of the changes come from downstream changes made in https://github.com/ziglang/zig/pull/18160 (to `Driver.zig` and `GenerateDef.zig`).
EDIT: Note that the ziglang.org CI is broken right now so there's no `master` binaries with the https://github.com/ziglang/zig/pull/18160 changes yet.
=> Update for latest Zig build system changes

src/aro/Diagnostics/messages.def, src/aro/Parser.zig, test/cases/complex numbers clang.c
Question: should this be its own Tree.Tag or should it reuse `.bit_not_expr`?
=> Parser: allow `~` operator for complex conjugation

src/aro/Parser.zig, test/cases/return.c, test/cases/unreachable code.c
resolve #619
The switch statement was not handled correctly by nodeIsNoreturn, since break and continue returned .yes like return_stmt that caused that it was treated like a return from the function instead of just exiting the switch statement.
Also added handling for the default statement for a simple switch+default, the case statement is not handled for now because it requires more complex reasoning when combined with multiple cases or with an default statement inside a compound statement, so it return the default .no value.
And changed the check of compound_stmt to try to find a statement with a return instead of just looking the last one.
Since switch_stmt no longer return .complex i have remove it for now, since if_then_else_stmt will no longer propagate it and no other statement use …
=> Parser: improve return detection for switch statments

src/aro/Hideset.zig, src/aro/Parser.zig, src/aro/Preprocessor.zig, src/aro/Tree.zig, src/aro/pragmas/gcc.zig, src/aro/pragmas/message.zig, src/aro/pragmas/once.zig, src/aro/pragmas/pack.zig, test/fuzz/fuzz_lib.zig, test/record_runner.zig, test/runner.zig
The main insight here is that most tokens don't have expansion locations; and that expansion locations are (currently) only used for diagnostic messages, so "slow" lookups are not a problem. Since tokens are always inserted in-order by the preprocessor (sorted by construction), we can store token index + expansion locations in a MultiArrayList and binary search for a token index when we want the corresponding expansion locations.
sqlite benchmark:
```
Benchmark 1 (47 runs): source/arocc/zig-out/bin/arocc -Wno-unreachable-code -fsyntax-only -I. sqlite3.c
measurement          mean ± σ            min … max           outliers         delta
wall_time           213ms ±  575us     211ms …  214ms          0 ( 0%)        0%
peak_rss           62.5MB ± 58.0KB    62.4MB … 62.6MB          0 ( 0%) …
```
=> Store expansion locations separately from tokens

include/stdckdint.h, src/aro/Diagnostics/messages.def, src/aro/Parser.zig, test/cases/ast/stdckdint_ast.c, test/cases/stdckdint.c, test/cases/stdckdint_ast.c
=> Parser: implement stdckdint.h

src/aro/Parser.zig, src/aro/Type.zig, test/cases/incomplete types.c
This checks before calling typeStr with the places that I could generate a crash, and adds a check for non-debug modes so that they'll return an obvious error instead of illegal behavior.
=> Add protection from calling `typeStr` with an invalid type

src/aro/Parser.zig, test/cases/redefinitions.c
=> Parser: skip enumerators which are redefinitions

src/aro/Compilation.zig, src/aro/Driver.zig, src/aro/Driver/GCCVersion.zig, src/aro/LangOpts.zig, src/aro/Toolchain.zig, src/aro/toolchains/Linux.zig, test/cases/gnuc version default.c, test/cases/gnuc version empty.c, test/cases/gnuc version override.c, test/record_runner.zig, test/runner.zig
This allows us to pretend to be GCC 4.2.1 by default, just like clang.
=> Compilation: set __GNUC__ and related macros

src/aro/Parser.zig, src/aro/Value.zig, test/cases/float values.c
Previously only worked for `-1.` (since 1 has its own tag).
=> Add unary minus support for float values

src/aro/Parser.zig, test/README.MD, test/cases/invalid attributes.c, test/runner.zig
This prevents the parser from getting confused about the number of fields if a parser error triggers `parseOrNextDecl` to skip to the next decl.
Fixes #639
=> Don't create implicit function definitions during record parsing

src/aro/Type.zig, test/cases/typeof pointer wrong size.c
Fixes a crash in the included test.
=> Type: handle typeof and attributed types in integerRank

src/aro/Compilation.zig, src/aro/Parser.zig, src/aro/Tokenizer.zig, src/aro/Tree/number_affixes.zig, src/aro/Type.zig, src/aro/target.zig, test/cases/__float80 clang.c, test/cases/__float80.c, test/cases/ast/__float80.c
Instead, it's a typedef for 80-bit extended double on platforms that support it, when emulating GCC.
Closes #641
=> Remove __float80 as a distinct type

src/aro/Tokenizer.zig, test/cases/spliced newline in string literal.c, test/spliced newline in char literal.c
Two backslashes followed by two newlines in a literal will result in backslash-newline after linesplicing. Treat this as an unterminated literal
Closes #644
=> Tokenizer: treat backslash-newline as an unterminated char/string literal

src/aro/Type.zig
Applies the change made to the aro source in ziglang/zig#19227.
=> make qual_handling enum for canonicalize() public

src/aro/SymbolStack.zig, src/aro/Type.zig, test/cases/redefine invalid typedef.c
Putting invalid typedefs into the symbol table is problematic because if they get redefined, we try to render the original type (not possible for invalid types) for the error message.
Closes #645
=> Parser: do not define typedefs with invalid types

src/aro/Attribute.zig, src/aro/Parser.zig, src/aro/Tree.zig, test/cases/warn unused result.c
Inspect the tree more closely to make sure we're accessing the correct data fields. Also adds result usage warnings/errors for calling function pointer fields of records.
Closes #653
=> Improve unused result diagnostics

src/aro/Attribute.zig, src/aro/Diagnostics.zig, src/aro/Diagnostics/messages.def
Tested manually since this is meant to be temporary but I can add test cases if you want.
=> Attribute: convert unimplemented attributes to errors instead of panics

src/aro/Tokenizer.zig, test/cases/colon after #embed.c
If a colon appeared at the end of an embed directive and was the last byte in a file, we would do an out of bounds read trying to tokenize a double colon.
=> Tokenizer: prevent OOB read when processing #embed directive

src/aro/Parser.zig, test/cases/generic.c
ensure list_buf and decl_buf have the same length before iterating over them to check for duplicate controlling expressions
Fixes #659
=> Parser: handle error during parsing of generic selection

src/aro/Parser.zig, test/cases/float values.c
Ensure that the value, if present, is zero or one.
Closes #668
=> Parser: boolcast lhs of logical `or` expression even if not evaluating it

src/aro/Preprocessor.zig, test/cases/stringify backslashes.c
If the stringify output ends with a backslash, retokenize it to determine if the final backslash is unpaired.
=> Preprocessor: trailing backslash in stringize output is allowed if escaped

src/aro/Value.zig, test/cases/binary expressions.c
bigint bitXor docs say that if exactly one argument is negative, we need an extra limb.
Closes #667
=> Value: allocate enough limbs for bitwise xor result

src/aro/Parser.zig, test/cases/binary expressions.c
=> Parser: don't create pointer-to-invalid via ampersand operator

src/aro/Parser.zig, test/cases/concat improperly encoded strings.c
=> Parser: don't concatenate improperly-encoded strings

build/GenerateDef.zig, src/aro/Value.zig, test/cases/complex values.c
We can't compare complex values; toFloat grabs just the real part. This logic will need to be updated when complex int values are supported.
Fixes #675
=> Value: compare for zero against float instead of Value

src/aro/Type.zig, test/cases/enum fixed.c
Fixes crashes with pointers to incomplete enums / fixed-underlying-type enums, and incorrect results when comparing enum types.
=> Enum fixes

src/aro/Diagnostics/messages.def, src/aro/Parser.zig, test/cases/enum fixed.c
=> Parser: require integral types for fixed-type enums

src/aro/LangOpts.zig, src/aro/Parser.zig, src/aro/Preprocessor.zig, src/aro/Tokenizer.zig, src/aro/Type.zig, test/cases/arithmetic overflow.c, test/cases/typeof incomplete array.c, test/record_runner.zig
Also includes an unrelated copy-paste fix for division overflow
=> Set size of typeof-incomplete arrays correctly

src/aro/Value.zig
This came up in fuzz testing, although I had trouble recreating with the standard test runner. This solution makes wide-string value printing slower but it's already on the debug path. There are other solutions (passing the alignment when calling intern or just aligning based on the byte length), but this seemed like the least invasive and doesn't involve extra storage.
=> Value: avoid unaligned loads when printing strings

src/aro/Parser.zig, test/cases/statement expressions.c
resolve #654
Add suffixExpr parsing after compoundStmt before returning in castExpr like it is done in unExpr, without that the expr returned without parsing the callExpr and, expecting the semicolon, it generated an error.
=> Parser: allow calling function via statement expression

src/aro/Driver.zig, src/aro/Driver/Filesystem.zig, src/aro/Driver/GCCDetector.zig, src/aro/Toolchain.zig, src/aro/toolchains/Linux.zig, test/record_runner.zig, test/runner.zig
Updates Aro in preparation for https://github.com/ziglang/zig/pull/19847.
This is mergable now; it will just avoid compile errors once that PR is merged.
EDIT: CI failure is unrelated and would be fixed by https://github.com/Vexu/arocc/pull/707/commits/97697e702408bcbe7850f8b9d9db6fcb88bea8be:
```
src/aro/target.zig:744:22: error: switch must handle all possibilities
/opt/hostedtoolcache/zig/master/x64/lib/std/Target.zig:652:5: note: unhandled enumeration value: 'ohos'
```
=> Fix usage of deprecated std lib APIs

src/aro/Diagnostics.zig, src/aro/Diagnostics/messages.def, src/aro/Parser.zig, src/aro/Value.zig, test/cases/assignment.c, test/cases/binary expressions.c, test/cases/constexpr.c, test/cases/enum overflow.c, test/cases/wide character constants.c
When I wanted to learn how to write a C23 C language compiler, this project was extremely helpful to me, no less than having a rich big meal right after finishing a workout. I've been going through this project almost commit by commit, although I haven't finished looking through it all yet. This project not only taught me how to write a C compiler for the C23 standard, but also allowed me to learn a new language, Ziglang, which made me feel very happy. So I want to see if I can do something for this project. I looked at the issue section, and because I don't have experience contributing to open-source projects, I can only start with issues labeled as good first issue.
so I attempted to solve this issue.  #701 
Value.intCast` currently  return a value that indicates whether truncation …
=> Parser: Report a Warning if implicit integer conversion truncates value or sign conversion.

src/aro/Compilation.zig, test/cases/#embed.c
Closes https://github.com/Vexu/arocc/issues/718
=> define __STDC macros from C23

src/aro/Compilation.zig
This kept tripping me up because I have my editor configured to eliminate trailing white space on save.
=> Get rid of a trailing space in `Compilation.zig`.

src/aro/Attribute.zig, src/aro/Compilation.zig, src/aro/target.zig
see [ziglang/zig#20802](https://github.com/ziglang/zig/pull/20820).
close #729
=> zig update: remove `aarch64_32` tag

src/aro/Type.zig, test/cases/double long.c
=> Type: allow `double long` and `_Complex double long`

src/aro/Builtins.zig, src/aro/Compilation.zig, src/aro/Preprocessor.zig, src/aro/Tokenizer.zig, src/aro/Value.zig, src/aro/toolchains/Linux.zig, src/main.zig, test/record_runner.zig, test/runner.zig
Removes a dependency on global system state. The primary usage would be a library that wants to use aro with an arbitrary working directory without actually having to change the working directory of the process.
=> Compilation: store cwd in Compilation

build.zig.zon
Not sure how to handle the `version` field - we also compute it in build.zig
=> Build: Add a build.zig.zon file

src/aro/Diagnostics.zig, src/aro/Diagnostics/messages.def, src/aro/Parser.zig, src/aro/Type.zig, test/cases/array argument is null.c, test/cases/array argument too small.c
Closes https://github.com/Vexu/arocc/issues/349
=> Check argument size on static array parameters

src/aro/Driver.zig, src/aro/Preprocessor.zig, test/cases/debug dump macro names.c, test/cases/debug dump macros and results.c, test/cases/debug dump macros.c, test/cases/expanded/debug dump macro names.c, test/cases/expanded/debug dump macros and results.c, test/cases/expanded/debug dump macros.c, test/runner.zig
Adds support for GCC's -dD, -dM, -dN flags which enable dumping macro names and/or definitions along with or instead of preprocessor output.
Added a `CHECK_PARTIAL_MATCH` option for preprocessor testing, because the output contains things like `__TIME__` which is difficult to fit into our existing preprocessor test framework.
`-dM` is also difficult to test extensively with the existing framework because it dumps the output in arbitrary order (just iterates over `pp.defines`) which seems to match the observed behavior of clang
=> Preprocessor: Add debug dump options

src/aro/Parser.zig, src/aro/Tree.zig, test/cases/ast/attributed record fields.c, test/cases/ast/cast kinds.c, test/cases/ast/complex init.c, test/cases/ast/generic ast.c, test/cases/ast/promotion edge cases.c, test/cases/ast/types.c, test/cases/generic ast.c
This is meant to be a quality-of-life improvement for aro consumers that addresses this comment: https://github.com/ziglang/zig/blob/a854ce3021773a3f5cd1dce8ac6bc9eb5f4f937c/lib/compiler/aro_translate_c.zig#L1034C32-L1034C38
While updating generic selections I noticed that some types were not correct so I updated those.
=> Store some tree nodes as [2]NodeIndex instead of bin with lhs,rhs.

src/aro/Compilation.zig, src/aro/Parser.zig, src/aro/Tree.zig
This closes #732 (although some node types do not have locations yet e.g. array and struct initializers)
As expected this increases memory usage but there's not much of a performance hit (numbers are for parsing `zig2.c` which is `161,279,661` bytes)
```
Before
measurement          mean ± σ            min … max           outliers         delta
wall_time          9.54s  ± 9.92ms    9.53s  … 9.55s           0 ( 0%)        0%
peak_rss           1.61GB ± 28.8KB    1.61GB … 1.61GB          0 ( 0%)        0%
cpu_cycles         36.9G  ± 40.2M     36.8G  … 36.9G           0 ( 0%)        0%
instructions       78.6G  ± 70.2      78.6G  … 78.6G           0 ( 0%)        0%
cache_references   93.3M  ±  399K     92.9M  … 93.7M           0 ( 0%)        0%
cache_misses       43.9M  ±  187K     43.6M  … …
```
=> Tree: add location for most nodes

deps/zig/arch/x86_64/Lower.zig, src/aro/Driver/Filesystem.zig, src/aro/Parser.zig
=> Zig update: change setCold to branchHint

src/aro/Attribute.zig, src/aro/Parser.zig, src/aro/Tree.zig, src/aro/Type.zig, src/aro/record_layout.zig, test/cases/nested attributes.c, test/record_runner.zig
The main change here is making `attributed` types nestable instead of trying to merge them into a single level. This fixed a few record tests as well - previously there were cases where attributes could get dropped via multiple layers of typedefs if each added its own attributes.
=> Rework attributes a bit

src/aro/SymbolStack.zig, src/aro/Tree.zig, src/aro/Type.zig, test/cases/ast/_Float16.c, test/cases/ast/__float80.c, test/cases/ast/types.c, test/cases/ast/vectors.c
Just an idea - as a stop-gap before #733 is implemented. This would allow more progress on aro translate-c since one blocker right now is the lack of typedef names. It was about 5 minutes of work so I'm not very strongly advocating for it if you think it's too much of a hack.
We had at least 4 bytes of padding available in `Type` because it doesn't change the size of `Type` in either Safe or Fast modes.
=> Type: add a name field to track typedef names

src/aro/Compilation.zig, src/aro/Driver.zig, src/aro/target.zig, src/backend.zig, src/backend/CodeGenOptions.zig, test/cases/pic1.c, test/cases/pic2.c, test/cases/pie1.c, test/cases/pie2.c
Some time (real soon now™) I'd like to start writing a simple AST -> x86_64 assembly backend. No IR or optimizations or anything, just something that generates readable/debuggable assembly. 
Is that something that you think should be part of aro? Or a separate project that uses aro as a dependency? If it's part of aro I'd want to put it behind a `-fsimple-asm` or similar type of flag.
=> Compilation: Add driver/frontend support for pic/pie options

src/aro/CodeGen.zig
This was caused by #750 ; not sure if there's an easy way to add a test at the moment. I tested manually with
```c
extern int printf(const char *restrict fmt, ...);
int main(void) {
int x = ({
printf("Hello, world!\n");
2;
});
return 0;
}
```
on x86_64 linux.
=> CodeGen: fix child nodes usage

src/aro/Diagnostics.zig, src/aro/Diagnostics/messages.def, src/aro/Parser.zig, src/aro/Type.zig, test/cases/gnu pointer arith.c
Closes https://github.com/Vexu/arocc/issues/759
In this request I implemented the ```Type.isPtrTo``` function but only for the ```.pointer``` type specifier. I'm not sure if it is right approach to do that. Maybe other specifiers should be considered as well. I'm open for the conversation.
=> Issue a warning on gnu void pointer arithmetic

src/aro/Diagnostics/messages.def, src/aro/Driver.zig, src/aro/target.zig
I tried to solve #770,  but full implementation of this function is too long.  So for now, i have only implemented these two target-related [default functions](https://github.com/llvm/llvm-project/blob/f12e10b513686a12f20f0c897dcc9ffc00cbce09/clang/lib/Driver/ToolChains/CommonArgs.cpp#L1808).
I'm unable to verify all the correctness.  Could please review this part first?  Once It's reviewed and passed, I'll submit the remaining code for `target.getPICMode` function.
=> Implement target.getPICMode

src/aro/Attribute.zig, src/aro/Compilation.zig, src/aro/Diagnostics/messages.def, src/aro/Parser.zig, src/aro/Tree.zig, src/aro/Value.zig, src/backend/Interner.zig, test/cases/const decl folding.c, test/cases/relocations.c
Add support for initializing pointers with, and doing static asserts with, offsets from global variables.
I'm very open to bikeshedding on names of things / code organization. I moved `StringInterner` to backend so that `Interner` could hold `StringId` values.
Open areas for enhancement:
* Should also support static variables and not just globals.
* Model relocation values with name + bigint instead of name + i64. Right now if the offset overflows we correctly warn but the printed diagnostic is incorrect since the value wraps around.
=> Start adding frontend support for relocations

src/aro/Parser.zig, src/backend/Object/Elf.zig, test/cases/fp16 parameter.c, test/runner.zig
https://github.com/Vexu/arocc/commit/59e6078df83e45e2898d89689ce8914e81bcb4ab moved the CI MacOS runner to aarch64 which broke `test/cases/arithmetic conversion floats.c`, this should fix it.
=> Fix long double casting when same size as double

src/aro/Parser.zig, src/aro/Tree.zig, src/aro/Value.zig, src/aro/target.zig, src/backend/Interner.zig, test/cases/ast/_Float16.c, test/cases/ast/stdckdint_ast.c, test/cases/relocations.c
Allow array-to-pointer decay to produce a pointer value
Handle address-of locals as well as globals
Rename "reloc" to pointer for consistency
=> Pointer value improvements

src/aro/Builtins.zig, src/aro/Compilation.zig, src/aro/Driver.zig, src/aro/Parser.zig, test/fuzz/fuzz_lib.zig, test/record_runner.zig, test/runner.zig
resolve #711
Added a new argument to generateBuiltinMacros to pass an optional timestamp that is used in the case of not having a valid epoch passed as environment variable, to generate the timestamp from a path  a new function called generateBuiltinMacrosFromPath is created and is used in Driver for each source file instead of having the same builtin.
Changed generateDateAndTime to make the timestamp argument optional, since the stat can fail, and following GCC behavior it will expand timestamp to "??? ??? ?? ??:??:?? ????"
=> Compilation: use mtime for timestamp macro

src/aro/Diagnostics/messages.def, src/aro/Parser.zig, src/aro/Tree.zig, src/aro/Value.zig, src/backend/Interner.zig, test/cases/ast/_Float16.c, test/cases/ast/c23 true false ast.c, test/cases/ast/complex init.c, test/cases/ast/decayed attributed array.c, test/cases/ast/float eval method.c, test/cases/ast/generic ast.c, test/cases/ast/native half type.c, test/cases/ast/promotion edge cases.c, test/cases/ast/stdckdint_ast.c, test/cases/constexpr.c
Initial work for solving #783
There are still some issues to solve regarding saving complex int values, pointers to compound literals, and accessing record fields in constexpr contexts, but I think this is enough that I can start working on a simple assembly backend.
=> Parser: save value for init nodes

build.zig, src/aro.zig, src/aro/Diagnostics/messages.def, src/aro/Driver.zig, src/aro/Toolchain.zig, src/aro/Tree.zig, src/aro/Value.zig, src/assembly_backend.zig, src/assembly_backend/x86_64.zig, src/backend.zig, src/backend/Assembly.zig, src/backend/CodeGenOptions.zig, src/main.zig
Some basic assembly codegen, tested with:
```c
/* main.c */
int printf(const char *fmt, ...);
extern char foo[];
extern int bar;
extern double baz;
int main(void)
{
printf("%s\n%d\n%lf\n", foo, bar, baz);
return 0;
}
```
```c
/* test.c */
char foo[] = "hello";
int bar = 42;
double baz = 3.14;
```
```sh-session
~$ gcc -c main.c
~$ arocc -O0 test.c main.o`
~$ ./a.out
hello
42
3.140000
```
I structured things the way I did so that `aro` (the frontend module) wouldn't depend on this assembly backend (as in, needing to import it so that it can call it from Driver). The way things are set up now, a do-nothing function can be passed as the final argument of `Driver.main`. But I'm not sure if that's the best way to achieve that.
My next goal is to get very basic function generation going and then …
=> backend: basic x86_64 assembly codegen for some global vars

src/aro/Diagnostics.zig, src/aro/Diagnostics/messages.def, src/aro/Parser.zig, test/cases/packed member address.c, test/cases/relocations.c
Closes https://github.com/Vexu/arocc/issues/788
=> Issue a warning on packed record member access

src/aro/CodeGen.zig, src/aro/Tree.zig, test/cases/ast/for decl stmt.c, test/cases/ast/forever stmt.c, test/cases/for decl stmt.c, test/cases/forever stmt.c, test/runner.zig
While working on the backend I found I needed a uniform way to iterate over child nodes. While implementing it I noticed that we didn't have any test cases that exercised `forever_stmt` or `for_decl_stmt` so I added those, and that we didn't support builtin call expressions in the `childNodes` function.
=> Add Tree iterator

src/aro/target.zig, test/record_runner.zig
I'll need to do some code archaeology to get the record-test-generator working again, so for now I'm just recording them as invalid tests so that they pass.
=> tests: update to new std.Target abis, and remove 32-bit CPU support for Apple platforms

src/aro/Type.zig, test/cases/duplicate typedef.c, test/cases/typedef extra specifiers disallowed.c
Closes #731
Previously we would allow things like:
```c
typedef long foo;
typedef unsigned foo bar;
```
To define `bar` as `unsigned long`. Seems reasonable but apparently not allowed by C.
=> Type: disallow type specifiers from combining with types specified by typedefed names

build/GenerateDef.zig, src/aro/Builtins/eval.zig, src/aro/Parser.zig
This enables using enum literals instead of `Builtin.tagFromName("str").?`.
=> GenerateDef: make tag enum exhaustive

src/aro/Attribute.zig, test/cases/compound stmt fallthrough.c
Previously we would not accept valid code; now we might accept some invalid constructs but a misplaced fallthrough attribute seems fairly harmless.
=> Attribute: allow fallthrough to precede closing braces

src/aro/Parser.zig, test/cases/undef.c
=> Parser: fix use-after-free from implicit typedefs when using -undef

src/aro/Compilation.zig, src/aro/Diagnostics.zig, src/aro/Driver.zig, src/aro/Toolchain.zig, src/aro/toolchains/Linux.zig, test/cases/hide warnings.c, test/record_runner.zig, test/runner.zig
I was reworking the build logic for `ziglang/translate-c`, and ultimately hit one bug and two missing features:
* Bug: `-w` does hide warnings, but *doesn't* hide their associated notes.
* Now, `Diagnostics` tracks whether it skipped the last diagnostic it was given, and if it did, it will also skip an immediately following note.
* Missing feature: there should be a way to tell Aro where its `include` directory is instead of having Aro search for it. This means Aro can be invoked programmatically *without* having to copy everything to an install prefix; particularly helpful when trying to run Aro through the Zig build system.
* I have introduced `--aro-include-dir=<dir>`, which uses the given path instead of searching for the `include` directory. This option is highly analagous to the Zig …
=> Some things for ziglang/translate-c

src/aro/TypeStore.zig
The source is Zig's `std.builtin.VaList`, which uses exactly this logic for ARM.
I have also tested translate-c cross-translating to arm-linux with this change applied, and varargs seem to work correctly.
=> TypeStore: add VaList for ARM

src/aro/Parser.zig, src/aro/Parser/Diagnostic.zig, test/cases/cast to same type.c
In general, casting to a non-scalar type is disallowed. However, casting to the same type can be treated as a no-op, which is what GCC and Clang do.
=> Parser: allow casting to the same non-scalar type as an extension

src/aro/Compilation.zig, src/aro/Driver.zig, src/backend/CodeGenOptions.zig, test/cases/no optimizations.c, test/cases/optimize define.c, test/cases/optimize size flags.c
Also fix a bug in Driver where `-O` would set optimization level 0. In GCC and clang it's equivalent to `-O1`
=> Define __OPTIMIZE__ and __OPTIMIZE_SIZE__ flags if relevant

src/aro.zig, src/aro/Compilation.zig, src/aro/Diagnostics.zig, src/aro/Driver.zig, src/aro/Driver/GCCVersion.zig, src/aro/LangOpts.zig, src/aro/Parser.zig, src/aro/text_literal.zig, test/cases/gnuc version default clang.c, test/cases/gnuc version default gcc.c, test/cases/gnuc version default msvc.c, test/cases/gnuc version default.c, test/runner.zig
1. Fixes a bug in Driver where an invalid gnuc_version would cause a crash when rendering the error (due to template `{0s}` not being found)
2. If no explicit gnuc_version is set, use the default for the emulated compiler - 4.2.1 for clang, 7.1 for GCC, 0 (none) for MSVC
3. Add `__ARO_EMULATE__` to facilitate testing
I believe this should fix #887
=> Compilation: Set gnuc_version based on emulated compiler

src/aro/Compilation.zig
In my project I'm using https://github.com/zig-gamedev/zphysics, which uses these defines to detect compilation with MSVC, in order to match vtable header sizes: https://github.com/zig-gamedev/zphysics/blob/87dbfd003e31623cede1137aa8a70f86619b5d5b/libs/JoltC/JoltPhysicsC.h#L47
The values are the same as the defaults that the clang MSVC driver uses.
=> Provide _MSC_VER and _MSC_FULL_VER in msvc emulation mode
