Vexu/arocc

src/Compilation.zig, src/LangOpts.zig, src/Parser.zig, src/Preprocessor.zig, src/Tokenizer.zig, src/Tree.zig, src/main.zig, test/README.MD, test/cases/c89 standard.c, test/cases/c99 standard.c, test/cases/gnu89 standard.c, test/runner.zig
Allows setting the language standard, which controls which keywords are recognized.
=> Add language options module

src/Diagnostics.zig, src/Parser.zig, test/cases/divide by zero.c, test/cases/typeof.c
=> Parser: Warn on divide or remainder by zero

src/Parser.zig, src/Type.zig, test/cases/vla.c, test/runner.zig
Adds a test that attempts to render the tree for all successful parses.
=> Type: dump correct field for VLAs

.gitattributes, README.md, build.zig, deps/zig/codegen/x86_64.zig, deps/zig/lib.zig, deps/zig/register_manager.zig, src/Codegen.zig, src/Compilation.zig, src/Object.zig, src/codegen/x86_64.zig, src/lib.zig, src/main.zig, src/object/Elf.zig, test/cases/hello world.c, test/runner.zig
It was pretty obvious that it most of Zig's backend would not be reusable we'll take what we can so that there'll be as little duplication as possible once Aro becomes a dependency for Zig.
Closes #20
=> Add codegen

src/Compilation.zig, src/Diagnostics.zig, src/Parser.zig, src/Pragma.zig, src/Preprocessor.zig, src/main.zig, src/pragmas/gcc.zig, src/pragmas/once.zig, test/cases/pragma during parsing.c, test/cases/pragma warning and error.c, test/cases/pragma without terminating newline.c, test/cases/type_resolution.c, test/runner.zig
Work in progress; revamping the pragma system to make it more accessible to the parser as well as more extensible (custom pragmas)
=> Refactor pragmas

src/Type.zig, test/cases/redefinitions.c
=> Type: compare array types using arrayLen and elemType

.gitignore, build.zig, test/README.MD, test/docker/fuzz/Dockerfile, test/fuzz.zig
Adds fuzz testing via AFL++
Code and instructions adapted from https://github.com/squeek502/zig-fuzzing-example
=> Testing: Add fuzz testing build target

src/Diagnostics.zig, src/Parser.zig, test/cases/incomplete types.c
=> Parser: check for incomplete types before attempting field access

src/Parser.zig, test/cases/signed remainder.c
=> Parser: handle remainder operator correctly for signed integers

src/Parser.zig, test/cases/deref void.c, test/cases/initializers.c
Fixes 2 issues related to void pointer and elements
=> Void cleanup

src/Type.zig, test/cases/typeof.c
=> Type: Treat decayed typeof-types as pointers in Type.sizeof

src/Parser.zig, test/cases/preprocessor binary operators.c
=> Parser: don't allow address-of in preprocessor expressions

src/Tokenizer.zig
keywords will never use characters outside the basic character set
so there's never a need to remap extended keywords.
=> Tokenizer: remove call to getTokenId for extended identifiers

src/Diagnostics.zig, src/Parser.zig, src/Preprocessor.zig, test/cases/pragma in macro middle.c, test/cases/pragma in macro start.c
=> Parser: disallow #pragma in macro expansions

src/Preprocessor.zig, src/Tokenizer.zig, test/cases/stringify invalid.c
=> Preprocessor: don't stringify invalid tokens

src/Tokenizer.zig
Subtracting codepoint_len from index is incorrect, since that might take
us back past the beginning of the buffer.
Instead, either update the state and set codepoint_len to zero
(so that the next iteration will try the same codepoint with a new
state); or set the token id directly and break, if there is only one
possible outcome.
=> Tokenizer: extended identifier fixes

src/Parser.zig, test/cases/initializers.c
=> Parser: void initlist is an error

src/Parser.zig, src/Type.zig, test/cases/typeof.c
=> Type: add helper function for anonymous records

src/Compilation.zig, src/Diagnostics.zig, src/Parser.zig, src/Preprocessor.zig, src/Source.zig, src/Tokenizer.zig, src/Tree.zig, src/main.zig, test/cases/macro redefinition.c, test/cases/macro unbalanced parens call.c, test/cases/pragma in macro middle.c, test/cases/pragma in macro start.c, test/cases/preprocessor binary operators.c, test/fuzz/fuzz_lib.zig, test/runner.zig
=> Change the way source locations are stored

src/Diagnostics.zig, src/Parser.zig, src/Source.zig, src/Tree.zig, test/cases/statement expressions.c
=> Parser: add support for statement expressions

.github/workflows/ci.yml, src/Diagnostics.zig, src/Parser.zig, src/Tree.zig, src/Type.zig, src/Value.zig, src/codegen/x86_64.zig, test/cases/casts.c
Closes #114
Closes #179
Closes #208
=> Rework constant value evaluation

src/Parser.zig, test/cases/assignment.c
=> Parser: prevent intCast of incomplete-size types

src/Type.zig, test/cases/incomplete types.c
=> Type: promote incomplete enums to int

build.zig, src/Attribute.zig, src/Compilation.zig, src/Diagnostics.zig, src/LangOpts.zig, src/Parser.zig, src/Preprocessor.zig, src/Tokenizer.zig, src/Tree.zig, src/Type.zig, src/main.zig, test/cases/alignment.c, test/cases/attribute errors.c, test/cases/attributes.c, test/cases/declspec.c, test/cases/deprecated vars.c, test/cases/enum attributes.c, test/cases/misplaced attribute.c, test/cases/no declspec.c, test/cases/standard attributes.c, test/cases/stringify invalid.c, test/cases/types.c
Based on doing this, I think we should probably do #40 first to make token locations better and make it easier to get the values we'll be working with.
=> Basic validation for `aligned` attribute

src/Attribute.zig, test/cases/alignment.c
=> Attribute: only parse aligned attribute if it's an int

src/Parser.zig, test/cases/incomplete types.c
=> Parser: treat records with incomplete-size fields as incomplete size

src/Parser.zig, test/cases/incomplete types.c
=> Parser: handle incomplete-size types used in switch statement

src/Diagnostics.zig, src/Parser.zig, src/Value.zig, test/cases/assignment.c, test/cases/binary expressions.c, test/cases/divide by zero.c, test/cases/float array size.c, test/cases/float to int.c
=> Value: handle float to int overflow

src/Parser.zig, test/cases/incomplete types.c
=> Parser: always check for incomplete size before Result intCast

src/Type.zig, test/cases/vla.c
=> Type: Fix sizeof calculation for array of incomplete-size items

src/Type.zig, test/cases/functions.c
=> Type: handle alignof calculation for unspecified_variable_len_array

src/Parser.zig, test/cases/attributes.c
=> Parser: fix lookup of attributed records

src/Parser.zig, test/cases/initializers.c
=> Allow non-aggregate record initializers

src/Attribute.zig, src/Diagnostics.zig, src/Parser.zig, test/cases/ast/types.c, test/cases/attribute errors.c, test/cases/attributes.c, test/cases/designated_init.c, test/cases/transparent_union.c
=> Validate attributes before applying them

src/Compilation.zig, src/Preprocessor.zig, src/Tokenizer.zig, test/cases/include/my_include.h, test/cases/include_next.c
=> Preprocessor: implement __has_include_next

src/main.zig
Not sure of the best way to add a test for this one, but I manually tested it and it reads from `-` if a file with that name exists in the current directory, otherwise from stdin.
=> CLI: Read from stdin if filename is "-" and no file with that name exists

src/Parser.zig, src/pragmas/pack.zig
Record layout needs to tell the difference between `pragma_pack` not set, and a `pragma_pack` value.
=> make pragma nullable

include/stddef.h, src/Builtins.zig, src/Parser.zig, src/Tokenizer.zig, src/Type.zig, test/cases/offsetof.c
add support for `bitoffsetof`
I took a best guess. If you imaged something else let me know, or fix it up the way you like it.
=> `__builtin_bitoffsetof` support

src/Compilation.zig, src/Parser.zig, src/record_layout.zig, test/cases/attributes.c
=> record layout

src/Type.zig, test/cases/msvc boolean bitfield.c
=> Type: _Bool on MSVC is 8 bits

src/Compilation.zig, src/Type.zig, src/record_layout.zig
Bitfield layout for msvc.
a few small changes to get more of the tests to pass.
I think this is about the end of what I can do w/ layout w/o some of the outstanding bugs/features being fixed.
=> msvc bitfield layout

src/Compilation.zig
The unicode standard allows a byte-order mark <U+FEFF> at the beginning
of a file (encoded as "\xEF\xBB\xBF" in UTF-8). We require UTF-8 encoding,
and endianness is irrelevant for UTF-8, so we should ignore it.
=> Compilation: ignore BOM at the beginning of a file

src/Compilation.zig, src/Diagnostics.zig, src/Type.zig, test/record_runner.zig, test/runner.zig
=> Type: `long long` and `double` alignment is 4 bytes on i386

src/Parser.zig, src/Type.zig, test/record_runner.zig
Use correct pointer size on gnux32 ABI
Pack all enums on hexagon
=> Layout fixes

src/Compilation.zig, src/Parser.zig, src/Type.zig, src/record_layout.zig
Pass & return by value when possible.
=> Update record layout to use fewer pointers

deps/zig/lib.zig, src/Builtins.zig, src/Compilation.zig, src/Driver.zig, src/Parser.zig, src/Type.zig, src/features.zig, src/main.zig, src/record_layout.zig, src/target.zig, test/record_runner.zig, test/runner.zig
* CType was moved to the stdlib
* std.sort.sort is now std.me.sort
* snake_case some enums
=> update to Zig changes

src/Parser.zig, test/cases/attributes.c, test/cases/comma operator.c
Additionally, fix an issue with attributes being misapplied to incomplete arrays.
=> Comma operator lval conversion fix

build.zig, src/Type.zig, src/object/Elf.zig, src/record_layout.zig, src/target.zig, test/record_runner.zig
Before: `zig build test  173.28s user 1.72s system 100% cpu 2:53.77 total`
After: `zig build test  275.01s user 3.01s system 1484% cpu 18.725 total`
=> Run layout tests in parallel

src/Diagnostics.zig, src/Parser.zig, src/Type.zig, test/cases/ast/cast kinds.c, test/cases/cast kinds.c, test/cases/cast to union.c
=> Parser: Add cast-to-union support

src/Diagnostics.zig, src/Parser.zig, src/Type.zig, test/cases/ast/_Float16.c, test/cases/ast/complex init.c, test/cases/complex init.c, test/cases/complex numbers clang.c, test/cases/complex numbers gcc.c
Add support for 2-element initlist for complex numbers + `__builtin_complex`
=> Improve complex number support

src/Diagnostics.zig, src/Type.zig, test/cases/missing type specifier.c, test/cases/missing type specifier_c2x.c
=> add C23 error diagnostic: missing type specifier

src/Builtins.zig, src/Compilation.zig, src/Driver.zig, test/cases/undef.c, test/record_runner.zig, test/runner.zig
=> Driver: implement `-undef` CLI option

src/aro/Preprocessor.zig
Closes #553. See https://github.com/Vexu/arocc/issues/553#issuecomment-1807069502 for some relevant details.
@Vexu unsure what you meant by inlining the loop btw, adding the `inline` keyword before the `for` results in
```
src\aro\Preprocessor.zig:3060:17: error: unable to resolve comptime value
inline for (bytes) |byte| switch (byte) {
^~~~~
```
Let me know if I was misinterpreting that.
=> Escape filename path in line markers

src/aro/Diagnostics/messages.def, src/aro/Driver.zig, src/aro/Parser.zig, src/aro/Type.zig, src/backend/Ir.zig, test/cases/__auto_type.c, test/cases/ast/_Float16.c, test/cases/ast/c23 auto.c, test/cases/ast/cast kinds.c, test/cases/ast/types.c, test/cases/ast/vectors.c, test/cases/c23 auto.c, test/cases/constexpr.c
=> Parser: implement C23 auto type inference

src/aro/Parser.zig, test/cases/casts.c
=> Parser: Issue a diagnostic for casting non-int-or-pointer to pointer

src/aro/Preprocessor.zig
Closes https://github.com/Vexu/arocc/issues/611
=> Preprocessor: fix coments after if preprocessor directives

src/aro/Diagnostics.zig, src/aro/Diagnostics/messages.def, src/aro/Parser.zig, test/cases/negative and too big shift count.c
Closes https://github.com/Vexu/arocc/issues/596
=> implement warnings for incorrect shift count

src/aro/Parser.zig, test/cases/char literal sign extension.c
=> Parser: sign extend char literal values when necessary

build.zig
I'm not sure if this is the correct solution; but without this it was generating a static library instead of a .c file.
=> Fix fuzz build

src/aro.zig, src/aro/Builtins/eval.zig, src/aro/Parser.zig, src/aro/Value.zig, src/aro/annex_g.zig, src/backend/Interner.zig, test/cases/ast/__float80.c, test/cases/ast/complex init.c, test/cases/complex init.c, test/cases/complex values.c, test/cases/float builtins.c
Still some work to do but this is a first pass at adding complex number support. Only floats currently, still need to handle int <-> complex and complex initializers (2-element init lists for complex produce a complex value)
=> Value: support complex values

src/aro/Parser.zig, test/cases/casts.c
=> Parser: do not attempt to cast floats to incomplete-size ints

build/GenerateDef.zig
See https://github.com/ziglang/zig/pull/19844
=> Update writeFile for latest Zig

build/GenerateDef.zig, src/aro/Diagnostics.zig, test/record_runner.zig, test/runner.zig
The runner isn't quite right yet - if you run with `zig build test -Dskip-record-tests=true` the output isn't correct.
=> Zig update: new progress implementation

src/aro/Preprocessor.zig
Context: https://github.com/ziglang/zig/pull/20927
=> Update for latest Zig

src/aro/Toolchain.zig, src/aro/target.zig
zig PR: https://github.com/ziglang/zig/pull/20894
=> zig update: use `Arch.isPowerPC()`

src/aro/Preprocessor.zig, src/aro/Tokenizer.zig
Context: https://github.com/ziglang/zig/pull/21373, also lead to CI failed.(#771)
zig: rework fuzzing api: https://github.com/ziglang/zig/pull/21370
=> Update the latest zig

src/aro/Compilation.zig, src/aro/target.zig
ref https://github.com/ziglang/zig/pull/21504
=> Zig update: updates for Android targets

src/aro/target.zig
=> zig update: remove shadermodel OS tag

src/aro/Driver/Filesystem.zig, src/aro/Toolchain.zig, src/main.zig
=> Filesystem: Filesystem holds a cwd instead of using std.fs.cwd()

src/aro/Attribute.zig, src/aro/Attribute/names.def, src/aro/Parser.zig, src/aro/Value.zig, test/cases/relocations.c, test/cases/strings.c
Fix some frontend crashes discovered while parsing sqlite3.c
=> Sqlite fixes

src/aro/Parser.zig, test/cases/pointer subtraction.c
=> Parser: allow pointer subtraction of differently-qualified types

src/aro/Diagnostics.zig, src/aro/Diagnostics/messages.def, src/aro/Parser.zig, test/cases/gnu designated init extension.c, test/cases/statements.c
Also add a warning for empty if bodies
=> Add support for GNU missing `=` in designators

build.zig.zon, src/aro/Parser.zig, src/aro/Preprocessor.zig
The corresponding changes were made here https://github.com/ziglang/zig/pull/23549
=> Enable build with zig master branch

src/aro/InitList.zig, src/aro/Parser.zig, src/aro/Parser/Diagnostic.zig, test/cases/complex values.c, test/cases/initializers.c, test/cases/parser using typeof types.c
This is one of the big blockers for https://github.com/ziglang/translate-c
Closes #842
=> Fix parsing of complicated initializers

src/aro/Parser.zig, test/cases/call undeclared function with invalid type.c
=> Parser: Do not attempt vararg promotion on invalid types

src/aro/Preprocessor.zig
The backslashes in the file path weren't escaped on Windows, causing CI failures on translate-c. More generally, file paths can contain essentially any byte on e.g. POSIX systems, so this string *must* be escaped.
=> Preprocessor: escape `__FILE__` properly

build.zig, build.zig.zon, build/GenerateDef.zig, src/aro/CodeGen.zig, src/aro/Compilation.zig, src/aro/Diagnostics.zig, src/aro/Driver.zig, src/aro/Driver/GCCDetector.zig, src/aro/Parser.zig, src/aro/Pragma.zig, src/aro/Preprocessor.zig, src/aro/Tokenizer.zig, src/aro/Tree.zig, src/aro/TypeStore.zig, src/aro/Value.zig, src/aro/pragmas/message.zig, src/aro/target.zig, src/aro/text_literal.zig, src/assembly_backend/x86_64.zig, src/backend/Interner.zig, src/backend/Ir.zig, src/backend/Object.zig, src/backend/Object/Elf.zig, src/main.zig, test/cases/ast/attributed record fields.c, test/cases/ast/decayed attributed array.c, test/cases/ast/types.c, test/fuzz/fuzz_lib.zig, test/record_runner.zig, test/runner.zig
Blocked on https://github.com/ziglang/zig/pull/24464
=> Update to writergate changes

src/aro/Parser.zig, src/aro/Parser/Diagnostic.zig, src/aro/TypeStore.zig, test/cases/__auto_type.c, test/cases/assignment.c, test/cases/non string attribute.c, test/cases/typeof.c
Closes https://github.com/Vexu/arocc/issues/422
=> Improve const assignment errors

src/aro/Compilation.zig, src/aro/Diagnostics.zig, src/aro/Driver.zig, src/aro/Preprocessor.zig, src/aro/Preprocessor/Diagnostic.zig, src/aro/Source.zig, test/cases/date expansion.c
=> Suppress warnings in system headers

src/aro/TypeStore.zig
https://github.com/ziglang/translate-c/issues/43
=> `TypeStore`: synchronize `__va_list_tag` logic with Zig's `std.builtin.VaList`
